### ISSUE TITLE
Allow anonymous users

### ISSUE THREAD

**Issue by kaelig** [guardian/gu-who#61]
Some users would prefer to not fill in their full name to stay anonymous (in order to avoid targeted bullying, recruiters, bot traffic…).

I was wondering if there could be a "anonymous" team that would wave the full name requirement.

**Comment by rtyley** [comment]
That makes sense. I'd like to encourage people to provide a fullname, because it is helpful, and many people are unaware/don't care that the field exists, but it shouldn't be a binding requirement - I don't want to be responsible for making online harassment easier.

_gu:who_ is trying to solve the _not-knowing-who-is-in-your-github-org_ problem, and setting a fullname helps with that... but so does the `users.txt` file, in that it provides a record of who 'sponsored' the inclusion of a person. You can always go and ask the sponsor who those people are. There are also some other cues, such as seeing what GitHub teams within the org a user is in.

Rather than requiring people to make an additional step, ie getting an administrator to add them to an "anonymous" team, I'd prefer to reduce the fullname requirement to a separate suggestion, eg:

```
Consider entering a full name in your [GitHub profile] to make it easier for
the other people in your organisation to recognise you.
```

**Comment by kaelig** [comment]
Interesting point.

For us the "full name" requirement should still be the norm, but we have about 5% of our users who desire to keep their last name private. Alternatively I can ask them to fill their username with whatever they like.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
